name: LEIHS/leihs/mail
windows:
  2:
    name: app
    command: |
      export LEIHS_MAIL_SMTP_PORT=32025
      export LEIHS_MAIL_POP3_PORT=32110
      ./bin/run
  3:
    name: SMTP
    command: |
      export LEIHS_MAIL_SMTP_PORT=32025
      export LEIHS_MAIL_POP3_PORT=32110
      ./scripts/run_fake_smtp
  5:
    name: psql
    command: |
      psql -d leihs
  6:
    name: db
    command: |
      cd database
  8:
    name: log
    command: |
      mkdir -p log && echo " " > log/debug.log && tail -f log/debug.log
