jobs:
  specs:
    name: Run specs
    run_when:
      any branch has been updated:
        type: branch
        include_match: ^.*$
    context:
      task_defaults:
        include:
          - cider-ci/database_task-component.yml
          - cider-ci/ruby-bundle_task-component.yml
          - cider-ci/server_task-component.yml
          - cider-ci/uberjar_task-component.yml
        traits:
          JDK 8: true
        environment_variables:
          MAIL_DIR: '{{CIDER_CI_WORKING_DIR}}'
          DATABASE_NAME: leihs_mail_{{CIDER_CI_TRIAL_ID}}
          LEIHS_DATABASE_URL: "jdbc:postgresql://localhost/{{DATABASE_NAME}}?max-pool-size=5"
          LEIHS_SECRET: '{{CIDER_CI_TRIAL_ID}}'
          RAILS_ENV: test
          RUBY: '{{RUBY_ENGINE}}-{{RUBY_VERSION}}'
          RUBY_ENGINE: ruby
          RUBY_VERSION: 2.6.0
        git_options:
          submodules:
            include_match: ^.*$

      tasks:
        unreachable smtp server spec:
          name: "Unreachable smtp server spec"
          scripts:
            test:
              body: |
                #!/usr/bin/env bash
                exit 0
