jobs:
  specs without fake smtp server:
    name: Run specs WITHOUT fake smtp server
    include: cider-ci/specs_job-defaults.yml
    context:
      tasks:
        unreachable smtp server spec:
          name: "Unreachable smtp server spec"
          scripts:
            test:
              body: |
                set -eux
                export PATH=~/.rubies/$RUBY/bin:$PATH
                bundle exec rspec ./spec/smtp_server_unreachable_spec.rb

  specs with fake smtp server:
    name: Run specs WITH fake smtp server
    include: cider-ci/specs_job-defaults.yml
    context:
      generate_tasks:
        include_match: spec/fake_smtp/.*_spec.rb
        scripts:
          test:
            body: |
              set -eux
              export PATH=~/.rubies/$RUBY/bin:$PATH
              bundle exec rspec $CIDER_CI_TASK_FILE
