jobs:

  build-mail-uberjar:
    name: Build mail uberjar
    run_when:
      any branch has been updated:
        type: branch
        include_match: ^.*$
    context: { include: cider-ci/uberjar_job-context.yml }

  specs-without-fake-smtp-server:
    name: Run specs WITHOUT fake smtp server
    include: cider-ci/specs_job-defaults.yml
    context: { include: cider-ci/specs-without-smtp_job-context.yml }

  specs-with-fake-smtp-server:
    name: Run specs WITH fake smtp server
    include: cider-ci/specs_job-defaults.yml
    context: { include: cider-ci/specs-without-smtp_job-context.yml }

  good-to-merge:
    name: ⚑ Good To Merge
    description: |
      This job depends on all other tests and checks
      and it will pass if and only if all dependencies have passed.
      Status of this job is **used by github's "branch protection"**!
    include: cider-ci/good-to-merge_job.yml

