jobs:
  specs without fake smtp server:
    name: Run specs WITHOUT fake smtp server
    run_when:
      any branch has been updated:
        type: branch
        include_match: ^.*$
    context:
      include: cider-ci/shared/task_defaults.yml
      task_defaults:
        include:
          - cider-ci/database_task-component.yml
          - cider-ci/ruby-bundle_task-component.yml
          - cider-ci/server_task-component.yml
          - cider-ci/uberjar_task-component.yml
      tasks:
        unreachable smtp server spec:
          name: "Unreachable smtp server spec"
          scripts:
            test:
              body: |
                set -eux
                export PATH=~/.rubies/$RUBY/bin:$PATH
                bundle exec rspec ./spec/smtp_server_unreachable_spec.rb

  specs with fake smtp server:
    name: Run specs WITH fake smtp server
    run_when:
      any branch has been updated:
        type: branch
        include_match: ^.*$
    context:
      generate_tasks:
        include_match: spec/fake_smtp/.*_spec.rb
      include: cider-ci/shared/task_defaults.yml
      task_defaults:
        include:
          - cider-ci/database_task-component.yml
          - cider-ci/fake-smtp-server_task-component.yml
          - cider-ci/ruby-bundle_task-component.yml
          - cider-ci/server_task-component.yml
          - cider-ci/uberjar_task-component.yml
        scripts:
          test:
            body: |
              set -eux
              export PATH=~/.rubies/$RUBY/bin:$PATH
              bundle exec rspec $CIDER_CI_TASK_FILE
