jobs:
  specs without fake smtp server:
    name: Run specs WITHOUT fake smtp server
    include: cider-ci/specs_job-defaults.yml
    context:
      tasks:
        unreachable smtp server spec:
          name: "Unreachable smtp server spec"
          scripts:
            test:
              body: |
                set -eux
                export PATH=~/.rubies/$RUBY/bin:$PATH
                export LEIHS_MAIL_SMTP_DOMAIN="example.com"
                bundle exec rspec ./spec/smtp_server_unreachable_spec.rb

  specs with fake smtp server:
    name: Run specs WITH fake smtp server
    include: cider-ci/specs_job-defaults.yml
    context:
      generate_tasks:
        include_match: spec/fake_smtp/.*_spec.rb
      task_defaults:
        include: cider-ci/fake-smtp-server_task-component.yml
        scripts:
          test:
            body: |
              set -eux
              export PATH=~/.rubies/$RUBY/bin:$PATH
              export LEIHS_MAIL_SMTP_DOMAIN="example.com"
              bundle exec rspec $CIDER_CI_TASK_FILE

  build-mail-uberjar:
    name: Build mail uberjar
    run_when:
      any branch has been updated:
        type: branch
        include_match: ^.*$
    context:
      task_defaults:
        environment_variables:
          LEIHS_MAIL_DIR: "{{CIDER_CI_WORKING_DIR}}"
        git_options:
          submodules:
            include_match: ^.*$
      tasks:
        build-mail-uberjar:
          name: "Build mail uberjar"
          include:
            - cider-ci/uberjar_task-component.yml
