SEND_FREQUENCY_IN_SECONDS = ENV['LEIHS_MAIL_SEND_FREQUENCY_IN_SECONDS'].to_i || 5
RETRY_FREQUENCY_IN_SECONDS = ENV['LEIHS_MAIL_RETRY_FREQUENCY_IN_SECONDS'].to_i || 10
MAXIMUM_TRIALS = ENV['LEIHS_MAIL_MAXIMUM_TRIALS'].to_i || 2

LOG_FILE_PATH = "#{Dir.pwd}/log/fake_smtp.log"
DELAY_LATENCY_IN_SECONDS = 5
